wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717138725
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 105
      3:
      - 23
      4: 3.10.0
      5: 0.17.0
      6: 4.36.2
      8:
      - 5
      13: linux-x86_64
